config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get 'about' => "homes#about"
  devise_for :users

  resources :users, only: [:index,:show,:edit,:update]
  resources :books, only: [:new,:create,:index,:show,:edit,:update,:destroy] do
    resources :book_comments, only: [:edit, :create, :update, :destroy]
    resource :book_favorite, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :book_favorites, dependent: :destroy

  def favorited_by?(n)
    book_favorites.exists?(user_id: n.id)
  end

  def comment_by?(user)
    book_comments.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  validates :comment, presence: true

  belongs_to :user
  belongs_to :book
end

app/models/book_favorite.rb
class BookFavorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :book_favorites, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    #comment = current_user.book_comments.new(book_comment_params)
    comment = BookComment.new(book_comment_params)
    comment.user_id = current_user.id
    comment.book_id = book.id
    if comment.save
      flash[:notice] = "投稿に成功したよ"
      redirect_to book_path(book)
    else
      flash[:notice] = "投稿に失敗したよ"
      redirect_to book_path(book)
    end
  end

  def edit
    #@book = Book.find(params[:id])
    @comment = BookComment.find(params[:id])
  end

  def update
    @book_comment = BookComment.find(params[:id])
    if @book_comment.update(book_comment_params)
      flash[:notice] = "変更できました"
      redirect_to book_path(params[:book_id])
    else
      flash.now[:notice] = "変更できなかったよ"
      @comment = BookComment.find(params[:id])
      render :edit
    end
  end

  def destroy
    comment = BookComment.find(params[:id])
    if comment.destroy
      flash[:notice] = "削除できたよ"
      redirect_to book_path(params[:book_id])
    else
      flash[:notice] = "削除できませんでした"
      redirect_to book_path(params[:book_id])
    end
  end


  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/book_favorites_controller.rb
class BookFavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.book_favorites.new(book_id: book.id)
    if favorite.save
      flash[:notice] = "いいねが追加されました"
      #redirect_to book_path(book)
      redirect_to request.referer
    else
      flash[:notice] = "いいねが追加できなかったよ"
      #redirect_to book_path(book)
      redirect_to request.referer
    end
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.book_favorites.find_by(book_id: book.id)
    if favorite.destroy
      flash[:notice] = "いいねを削除しました"
      #redirect_to book_path(book)
      redirect_to request.referer
    else
      flash[:notice] = "いいねを削除できませんでした"
      #redirect_to book_path(book)
      redirect_to request.referer
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "投稿に成功したよ"
      redirect_to book_path(@book.id)
    else
      @hon = Book.all
      flash.now[:notice] = "投稿に失敗しました"
      render :index
    end
  end

  def index
    @hon = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "変更できたよ"
      redirect_to book_path(@book.id)
    else
      flash[:notice] = "変更できなかったよ"
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      flash[:notice] = "削除できたよ"
      redirect_to books_path
    else
      flash[:notice] = "削除できなかったよ"
      render :show
    end
  end


  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "変更できたよ"
      redirect_to books_path
    else
      #@user = User.find(params[:id])
      flash.now[:notice] = "変更できなかったよ"
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:image,:name,:introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to users_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/book_favorites_helper.rb
module BookFavoritesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/edit.html.erb
<h1>コメント編集</h1>

<%= form_with model: [@comment.book, @comment] ,method: :patch do |f| %>
  <h4>コメント</h4>
  <%= f.text_area :comment %>

  <%= f.submit "保存" %>
<% end %>
<br>
<%= link_to book_path(@comment.book.id) do %>
  <button type="button" class="btn btn-outline-primary">戻る</button>
<% end %>

app/views/books/_form.html.erb
<h2>新規投稿</h2>

<% if book.errors.any? %>
  <h3><%= book.errors.count %>件のエラーが発生しました。</h3>
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: book do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>感想</h4>
  <%= f.text_field :body %>

  <%= f.submit "投稿" %>
<% end %>

app/views/books/_info.html.erb
<div class = "container">
  <div class = "row">
    <h2>ログインユーザー</h2>
    <%= link_to user_path(current_user.id) do %>
      <%= image_tag current_user.get_image(100, 100) %>
    <% end %>
    <table>
      <tr>
        <td>名前</td>
        <td>
          <%= link_to user_path(current_user.id) do %>
            <%= current_user.name %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>紹介</td>
        <td><%= current_user.introduction %></td>
      </tr>
    </table>
  </div>
  <div class = "row">
    <%= link_to edit_user_path(current_user) do %>
      <button type="button" class="btn btn-outline-secondary ">
        <i class="fa-solid fa-user-gear"></i>
      </button>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<h1>編集</h1>

<% if @book.errors.any? %>
  <h3><%= @book.errors.count %>件のエラーが発生しました。</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>感想</h4>
  <%= f.text_field :body %>

  <%= f.submit "保存" %>
<% end %>
<br>
<%= link_to  book_path(@book.id) do %>
  <button type="button" class="btn btn-outline-primary">戻る</button>
<% end %>

app/views/books/index.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-md-4">
      <div class = "container">
        <div class = "row">
          <%= render "info" %>
        </div>
        <div class = "row">
          <%= render "form" ,book: @book %>
        </div>
      </div>
    </div>
    <div class = "col-md-8">
      <h1>投稿一覧</h1>
      <table>
          <thead>
            <tr>
              <th>投稿者</th>
              <th>プロフィール画像</th>
              <th>本のタイトル</th>
              <th>感想</th>
              <th>いいね</th>
              <th>コメント</th>
            </tr>
          </thead>
          <tbody>
            <% @hon.each do |book| %>
             <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= book.user.name %>
                  <% end %>
                </td>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= image_tag book.user.get_image(100,100) %>
                  <% end %>
                </td>
               <td>
                 <%= link_to book_path(book.id) do %>
                   <%= book.title %>
                 <% end %>
               </td>
               <td><%= book.body %></td>
               <td>
                 <% if book.favorited_by?(current_user) %>
                   <p>
                     <%= link_to book_book_favorite_path(book), method: :delete do %>
                      <i class="fa-solid fa-heart"></i>
                      <%= book.book_favorites.count %>
                     <% end %>
                   </p>
                  <% else %>
                   <p>
                     <%= link_to book_book_favorite_path(book), method: :post do %>
                      <i class="fa-regular fa-heart"></i>
                      <%= book.book_favorites.count %>
                     <% end %>
                   </p>
                 <% end %>
               </td>
               <td>
                 <% if book.comment_by?(current_user) %>
                   <%= link_to book_path(book.id) do %>
                     <i class="fa-solid fa-comment"></i>
                     <%= book.book_comments.count %>
                   <% end %>
                  <% else %>
                   <%= link_to book_path(book.id) do %>
                     <i class="fa-regular fa-comment"></i>
                     <%= book.book_comments.count %>
                   <% end %>
                 <% end %>
               </td>
             </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Book detail</h1>

<div class = "container">
<div class = "row">
  <div class = "col-md-9">
  <table>
    <thead>
      <tr>
        <th>投稿ユーザー</th>
        <th>タイトル</th>
        <th>感想</th>
        <% if @book.user == current_user %>
          <th></th>
          <th></th>
        <% end %>
        <th>コメント</th>
        <th>いいね</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <%= link_to user_path(@book.user.id) do %>
            <%= image_tag @book.user.get_image(100,100) %>
            <br>
            <%= @book.user.name %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(@book.id) do %>
            <%= @book.title %>
          <% end %>
        </td>
        <td><%= @book.body %></td>
        <% if @book.user == current_user %>
          <td>
            <%= link_to book_path(@book.id) ,method: :delete do %>
              <button type="button" class="btn btn-danger">削除</button>
            <% end %>
          </td>
          <td>
            <%= link_to edit_book_path(@book.id) do %>
              <button type="button" class="btn btn-info">編集</button>
            <% end %>
          </td>
        <% end %>
        <td>
          <div>
            <p>コメント件数：<%= @book.book_comments.count %></p>
            <% @book.book_comments.each do |book_comment| %>
              <p><%= book_comment.user.name %></p>
              <%= book_comment.created_at.strftime("%Y/%m/%d") %>
              <%= book_comment.comment %>
              <% if book_comment.user == current_user %>
                <%= link_to "編集" , edit_book_book_comment_path(book_comment.book, book_comment) %>
                <%= link_to "削除" , book_book_comment_path(book_comment.book, book_comment), method: :delete %>
              <% end %>
            <% end %>
          </div>
        </td>
        <td>
          <% if @book.favorited_by?(current_user) %>
            <p>
              <%= link_to book_book_favorite_path(@book), method: :delete do %>
                <i class="fa-solid fa-heart"></i>
                <%= @book.book_favorites.count %>
              <% end %>
            </p>
          <% else %>
            <p>
              <%= link_to book_book_favorite_path(@book), method: :post do %>
                <i class="fa-regular fa-heart"></i>
                <%= @book.book_favorites.count %>
              <% end %>
            </p>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  </div>

  <div class = "col-md-3">
    <h2>新規コメント</h2>
    <%= form_with model: [@book, @book_comment] do |f| %>
      <%= f.text_area :comment, rows: "5", placeholder: "コメントをここに" %>
      <%= f.submit "投稿" %>
    <% end %>
  </div>

</div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row-lg-3">
    <h1>welcome to <i class="fa-solid fa-book"></i> Bookers!!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row-lg-3">
    <h1>welcome to <i class="fa-solid fa-book"></i> Bookers!!</h1>
    <p>In <i class="fa-solid fa-book"></i> <b>Bookers</b> </p>
  </div>
  <div class="row-lg-3">
    <p>you can share and exchange your opinions , inpressions , and emotons</p>

    <p>about various books!</p>
  </div>

  <div class="row-lg-4">
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-block" %>
    <br>
    <%= link_to "Log in" , new_user_session_path, class: "btn btn-info btn-block" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers21</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/d81676dda2.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">

        <header>

          <% if user_signed_in? %>
            <li><%= link_to "ホーム", about_path %></li>
            <li><%= link_to "ユーザー", users_path %></li>
            <li><%= link_to "ブック", books_path %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "ホーム", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "サインアップ", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
          <% end %>
        </header>

        <main>
        <%= flash[:notice] %>
        <%= yield %>
        </main>

        <footer>
          <div class="container">
            <div class="row">
              <p>CopyRight Infratop.inc</p>
            </div>
          </div>
        </footer>

    </div>
  </body>
</html>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>

<% if @user.errors.any? %>
  <p><%= @user.errors.count %>件のエラーが発生しました。</p>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>
  <label>プロフィール画像</label>
    <%= f.file_field :image, placeholder: "プロフィール画像", acxept: "image/*" %>
  <label>名前</label>
    <%= f.text_field :name %>
  <label>紹介文</label>
    <%= f.text_field :introduction %>

  <%= f.submit "変更" %>
  <%= link_to "キャンセル", books_path %>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>プロフィール画像</th>
      <th>紹介文</th>
      <th></th>
    </tr>
  </thead>
  <% @user.each do |user| %>
  <tbody>
    <tr>
      <td>
        <%= link_to user_path(user.id) do %>
          <%= user.name %>
        <% end %>
      </td>
      <td><%= image_tag user.get_image(100,100) %></td>
      <td><%= user.introduction %></td>
      <td>
        <% if user == current_user %>
          <%= link_to edit_user_path(user.id) do %>
          <button type="button" class="btn btn-outline-secondary">
            <i class="fa-solid fa-user-gear"></i>
          </button>
          <% end %>
        <% end %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/users/show.html.erb
<h1>ユーザーページ</h1>
<br>
<table>
  <tr>
    <th>プロフィール画像</th>
    <th>名前</th>
    <th>紹介文</th>
    <th></th>
  </tr>
  <tr>
    <th><%= image_tag @user.get_image(100,100) %></th>
    <th><%= @user.name %></th>
    <th><%= @user.introduction %></th>
    <th>
      <% if @user == current_user %>
        <%= link_to edit_user_path(@user.id) do %>
          <button type="button" class="btn btn-outline-secondary">
            <i class="fa-solid fa-user-gear"></i>
          </button>
        <% end %>
      <% end %>
    </th>
  </tr>
</table>
<br>
<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>感想</th>
    </tr>
  </thead>
  <% @book.each do |book| %>
  <tbody>
    <tr>
      <th>
        <%= link_to book_path(book.id) do %>
          <button type="button" class="btn btn-outline-primary">
            <%= book.title %>
          </button>
        <% end %>
      </th>
      <th>
        <%= book.body %>
      </th>
      <th>
        <% if book.favorited_by?(current_user) %>
          <p>
           <%= link_to book_book_favorite_path(book), method: :delete do %>
             <i class="fa-solid fa-heart"></i>
             <%= book.book_favorites.count %>
          　<% end %>
          </p>
        <% else %>
          <p>
           <%= link_to book_book_favorite_path(book), method: :post do %>
            <i class="fa-regular fa-heart"></i>
            <%= book.book_favorites.count %>
           <% end %>
          </p>
        <% end %>
      </th>
      <th>
        <% if book.comment_by?(current_user) %>
         <%= link_to book_path(book.id) do %>
          <i class="fa-solid fa-comment"></i>
          <%= book.book_comments.count %>
         <% end %>
        <% else %>
         <%= link_to book_path(book.id) do %>
          <i class="fa-regular fa-comment"></i>
          <%= book.book_comments.count %>
         <% end %>
        <% end %>
      </th>
    </tr>
  </tbody>
  <% end %>
</table>